name: appointments
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  url_launcher: ^6.0.20
  intl: any
  flutter_advanced_drawer: any
  file_picker: any
  flutter_secure_storage: any
  firebase_auth: any
  cloud_firestore: any
  firebase_core: any
  firebase_storage: any
  permission_handler: any
  icons_launcher: any
  firebase_messaging: any
  flutter_local_notifications: any
  flutter_phoenix: any

# Path to the app icon for the `icons_launcher` package
icons_launcher:
  image_path: "resources/logo-apps.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  # Example:
  # assets:
  #   - images/logo.png

  # To include fonts, specify them below
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
